name: Node CMI # name

on: # event emitter of workflow
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: # work of workflow
  build:
    runs-on: ubuntu-latest # platform

    steps: # actions of build
      - uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install
      - run: npm run build --prefix client

  # deploy:
  # needs:build
